-- liquibase formatted sql


-- changeset przemyslaw.nosek:1697574293000-1
CREATE TABLE food
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid          VARCHAR(100),
    name          VARCHAR(100),
    energy        DECIMAL,
    carbohydrate  DECIMAL,
    sugar         DECIMAL,
    protein       DECIMAL,
    fat           DECIMAL,
    saturated_fat DECIMAL,
    fiber         DECIMAL,
    salt          DECIMAL,
    size          DECIMAL,
    unit          VARCHAR(20),
    producer      VARCHAR(100),
    allergens     VARCHAR(255),
    verified      BOOLEAN,
    created_by    VARCHAR(100),
    verified_by   VARCHAR(100)
);

ALTER TABLE food
    ALTER COLUMN created_by SET NOT NULL;

CREATE COLLATION ignore_accents (provider = icu, locale = 'und-u-ks-level1-kc-true', deterministic = false);

CREATE EXTENSION IF NOT EXISTS unaccent;