eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: additional-user-data-service
          uri: lb://additional-user-data-service
          predicates:
            - Path=/users/**
        - id: measurement-service
          uri: lb://measurement-service
          predicates:
            - Path=/measurements/**
        - id: food-service
          uri: lb://food-service
          predicates:
            - Path=/foods/**


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /users/v3/api-docs
        name: Additional User Data Service
      - url: /measurements/v3/api-docs
        name: Measurement Service
      - url: /foods/v3/api-docs
        name: Food Service
