spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/healthy-lifestyle
          jwk-set-uri: http://localhost:8181/realms/healthy-lifestyle/protocol/openid-connect/certs
server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka