-- liquibase formatted sql


-- changeset przemyslaw.nosek:1697528066000-1
CREATE TABLE additional_user_data
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid VARCHAR(100),
    phone_number VARCHAR(25),
    age INTEGER,
    gender VARCHAR(20),
    allergens VARCHAR(255)
);
